.TH midilooper 1
.SH NAME
midilooper \- midi loop sequencer
.SH SYNOPSIS
.B midilooper
[\fI\,OPTION\/\fR] ... [\fI\,FILEPATH\/\fR]
.SH DESCRIPTION
.PP
Loop midi sequencer controlled with interface, (keyboard or midi note and prog).
.SH OPTION
.TP
\fB\-a\fR, \fB\-\-alsa\fR
Alsa mode (default)
.TP
\fB\-f\fR, \fB\-\-file\fR \fIFILEPATH\fR
Load FILEPATH (midi file)
.TP
\fB\-h\fR, \fB\-\-help\fR
Display this help
.TP
\fB\-i\fR, \fB\-\-interface-help\fR
Display interface help
.TP
\fB\-j\fR, \fB\-\-jack\fR
Jack mode
.TP
\fB\-n\fR, \fB\-\-name \fINAME\fR
Set the midi client name (alsa or jack)
.SH AUTHOR
Written by Gilbert Romer
